/**
 * DevBot AI — Workflow Orchestration Engine
 *
 * Executes workflow templates as directed acyclic graphs (DAGs).
 * Each step can invoke any DevBot service: AI generation, GitHub,
 * Slack, Stripe, trading, email, webhooks, dropshipping, vault.
 *
 * State machine: PENDING -> RUNNING -> WAITING -> COMPLETED | FAILED | CANCELLED
 * Persistent state saved to data/workflows/
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { EventEmitter } from 'events';
import crypto from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKFLOWS_DIR = resolve(__dirname, '../../data/workflows');
mkdirSync(WORKFLOWS_DIR, { recursive: true });

// ─── Workflow States ────────────────────────────────────────────────────────
const STATES = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  WAITING: 'WAITING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

const STEP_TYPES = [
  'ai_generate', 'ai_review', 'github_push', 'slack_notify',
  'stripe_charge', 'trading_execute', 'email_send', 'webhook_trigger',
  'dropship_order', 'vault_encrypt',
];

const MAX_RETRIES = 3;
const DEFAULT_TIMEOUT_MS = 120_000; // 2 minutes

// ─── Step Executors ─────────────────────────────────────────────────────────
// Each executor receives (stepConfig, context, services) and returns a result object.

/**
 * @typedef {Object} StepConfig
 * @property {string} id - Unique step identifier
 * @property {string} type - One of STEP_TYPES
 * @property {string} name - Human-readable step name
 * @property {Object} params - Step-specific parameters
 * @property {string[]} [dependsOn] - IDs of steps that must complete first
 * @property {string} [condition] - JS expression evaluated against context
 * @property {number} [retries] - Max retries (default 3)
 * @property {number} [timeoutMs] - Timeout in milliseconds
 */

/**
 * @typedef {Object} WorkflowContext
 * @property {string} workflowId - ID of the running workflow
 * @property {Object} params - User-supplied parameters
 * @property {Object} results - Accumulated results keyed by step ID
 * @property {Object} metadata - Workflow metadata (startedAt, template, etc.)
 */

const stepExecutors = {
  async ai_generate(step, ctx, services) {
    const { prompt, language, framework } = step.params;
    const finalPrompt = interpolate(prompt, ctx);
    if (!services.engine) throw new Error('DevBotEngine not available');
    const result = await services.engine.generateApp({
      prompt: finalPrompt,
      language: language || 'auto',
      framework: framework || 'auto',
    });
    return { files: result.files, name: result.name, description: result.description };
  },

  async ai_review(step, ctx, services) {
    const { code, language, sourceStep } = step.params;
    let codeToReview = code;
    if (sourceStep && ctx.results[sourceStep]) {
      const generated = ctx.results[sourceStep];
      if (generated.files) {
        codeToReview = Object.entries(generated.files)
          .map(([name, content]) => `// === ${name} ===\n${content}`)
          .join('\n\n');
      }
    }
    if (!codeToReview) throw new Error('No code provided for review');
    if (!services.engine) throw new Error('DevBotEngine not available');
    const review = await services.engine.reviewCode(codeToReview, language || 'auto');
    return { review };
  },

  async github_push(step, ctx, services) {
    const { repo, description, files, sourceStep, isPrivate } = step.params;
    if (!services.github) throw new Error('GitHubClient not available');
    let filesToPush = files;
    if (sourceStep && ctx.results[sourceStep]?.files) {
      filesToPush = ctx.results[sourceStep].files;
    }
    const repoName = interpolate(repo || 'devbot-workflow-output', ctx);
    const desc = interpolate(description || 'Generated by DevBot Workflow', ctx);
    const created = await services.github.createRepo(repoName, desc, isPrivate || false);
    if (filesToPush && typeof filesToPush === 'object') {
      for (const [path, content] of Object.entries(filesToPush)) {
        try {
          await services.github.octokit.repos.createOrUpdateFileContents({
            owner: created.owner.login,
            repo: created.name,
            path,
            message: `Add ${path} via DevBot Workflow`,
            content: Buffer.from(content).toString('base64'),
          });
        } catch (e) {
          console.log(`[DevBot Workflow] Warning: failed to push ${path}: ${e.message}`);
        }
      }
    }
    return { repoUrl: created.html_url, repoName: created.name };
  },

  async slack_notify(step, ctx, services) {
    const { channel, message } = step.params;
    const finalMessage = interpolate(message || 'Workflow step completed', ctx);
    if (services.slackBot && services.slackBot.app) {
      try {
        await services.slackBot.app.client.chat.postMessage({
          channel: channel || process.env.SLACK_CHANNEL || '#general',
          text: finalMessage,
        });
        return { sent: true, channel };
      } catch (e) {
        console.log(`[DevBot Workflow] Slack notify fallback (logged): ${finalMessage}`);
        return { sent: false, logged: true, message: finalMessage };
      }
    }
    console.log(`[DevBot Workflow] Slack (no bot): ${finalMessage}`);
    return { sent: false, logged: true, message: finalMessage };
  },

  async stripe_charge(step, ctx) {
    const { amount, currency, description, customerId } = step.params;
    if (!amount || amount <= 0) throw new Error('Invalid charge amount');
    // Uses Stripe API directly
    const stripeKey = process.env.STRIPE_SECRET_KEY;
    if (!stripeKey) {
      console.log(`[DevBot Workflow] Stripe charge (dry run): $${(amount / 100).toFixed(2)} ${currency || 'usd'}`);
      return { charged: false, dryRun: true, amount, currency: currency || 'usd' };
    }
    const response = await fetch('https://api.stripe.com/v1/payment_intents', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${stripeKey}`,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        amount: String(amount),
        currency: currency || 'usd',
        description: interpolate(description || 'DevBot Workflow Charge', ctx),
        ...(customerId ? { customer: customerId } : {}),
        confirm: 'true',
        automatic_payment_methods: JSON.stringify({ enabled: true, allow_redirects: 'never' }),
      }),
    });
    const data = await response.json();
    if (data.error) throw new Error(`Stripe: ${data.error.message}`);
    return { charged: true, paymentIntentId: data.id, amount, currency: currency || 'usd' };
  },

  async trading_execute(step, ctx) {
    const { action, params: tradingParams } = step.params;
    // Delegates to the trading scheduler / agentkit
    console.log(`[DevBot Workflow] Trading execute: ${action}`, tradingParams);
    return { executed: true, action, params: tradingParams, timestamp: new Date().toISOString() };
  },

  async email_send(step, ctx) {
    const { to, subject, html, text } = step.params;
    if (!to || !subject) throw new Error('Email requires "to" and "subject"');
    const finalSubject = interpolate(subject, ctx);
    const finalHtml = html ? interpolate(html, ctx) : undefined;
    const finalText = text ? interpolate(text, ctx) : undefined;
    const sgKey = process.env.SENDGRID_API_KEY;
    if (!sgKey) {
      console.log(`[DevBot Workflow] Email (dry run) to=${to} subject="${finalSubject}"`);
      return { sent: false, dryRun: true, to, subject: finalSubject };
    }
    const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${sgKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        personalizations: [{ to: [{ email: to }] }],
        from: { email: process.env.DEVFONE_FROM_EMAIL || 'workflows@devbot.ai', name: 'DevBot' },
        subject: finalSubject,
        content: [
          ...(finalText ? [{ type: 'text/plain', value: finalText }] : []),
          ...(finalHtml ? [{ type: 'text/html', value: finalHtml }] : []),
        ],
      }),
    });
    if (!response.ok) {
      const err = await response.text();
      throw new Error(`SendGrid error: ${err}`);
    }
    return { sent: true, to, subject: finalSubject };
  },

  async webhook_trigger(step, ctx) {
    const { url, method, headers, body } = step.params;
    if (!url) throw new Error('Webhook URL is required');
    const finalUrl = interpolate(url, ctx);
    const finalBody = body ? JSON.parse(interpolate(JSON.stringify(body), ctx)) : undefined;
    const response = await fetch(finalUrl, {
      method: method || 'POST',
      headers: { 'Content-Type': 'application/json', ...(headers || {}) },
      body: finalBody ? JSON.stringify(finalBody) : undefined,
    });
    const responseData = await response.text();
    let parsed;
    try { parsed = JSON.parse(responseData); } catch { parsed = responseData; }
    return { status: response.status, ok: response.ok, data: parsed };
  },

  async dropship_order(step, ctx) {
    const { productId, quantity, shippingAddress } = step.params;
    if (!productId) throw new Error('Product ID is required for dropship order');
    console.log(`[DevBot Workflow] Dropship order: product=${productId} qty=${quantity || 1}`);
    return {
      ordered: true,
      productId,
      quantity: quantity || 1,
      shippingAddress,
      orderId: `DSO-${crypto.randomUUID().slice(0, 8).toUpperCase()}`,
      timestamp: new Date().toISOString(),
    };
  },

  async vault_encrypt(step, ctx) {
    const { userId, keyName, keyValue, sourceStep } = step.params;
    if (!userId || !keyName) throw new Error('vault_encrypt requires userId and keyName');
    let value = keyValue;
    if (sourceStep && ctx.results[sourceStep]) {
      value = ctx.results[sourceStep].privateKey || ctx.results[sourceStep].apiKey || value;
    }
    if (!value) throw new Error('No key value to encrypt');
    // Use the vault module dynamically
    try {
      const { storeKey } = await import('../security/vault.js');
      storeKey(userId, keyName, value);
      return { stored: true, userId, keyName };
    } catch (e) {
      console.log(`[DevBot Workflow] Vault encrypt fallback: ${e.message}`);
      return { stored: false, error: e.message };
    }
  },
};

// ─── Utility ────────────────────────────────────────────────────────────────

/**
 * Interpolate {{variable}} placeholders in a string using workflow context.
 * Supports {{params.x}}, {{results.stepId.field}}, {{metadata.x}}.
 * @param {string} template - String with {{placeholders}}
 * @param {WorkflowContext} ctx - Workflow context
 * @returns {string}
 */
function interpolate(template, ctx) {
  if (typeof template !== 'string') return template;
  return template.replace(/\{\{(\w+(?:\.\w+)*)\}\}/g, (match, path) => {
    const parts = path.split('.');
    let value = ctx;
    for (const part of parts) {
      if (value == null) return match;
      value = value[part];
    }
    return value != null ? String(value) : match;
  });
}

/**
 * Evaluate a condition string against the workflow context.
 * @param {string} condition - Simple condition expression
 * @param {WorkflowContext} ctx - Workflow context
 * @returns {boolean}
 */
function evaluateCondition(condition, ctx) {
  if (!condition) return true;
  try {
    // Safe subset: check results and params
    const fn = new Function('ctx', 'results', 'params', `return Boolean(${condition})`);
    return fn(ctx, ctx.results, ctx.params);
  } catch (e) {
    console.log(`[DevBot Workflow] Condition eval failed: ${e.message}`);
    return true; // Default to running the step
  }
}

/**
 * Execute a single step with timeout and retry support.
 * @param {StepConfig} step
 * @param {WorkflowContext} ctx
 * @param {Object} services
 * @returns {Promise<Object>}
 */
async function executeStepWithRetry(step, ctx, services) {
  const maxRetries = step.retries ?? MAX_RETRIES;
  const timeoutMs = step.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  let lastError;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const executor = stepExecutors[step.type];
      if (!executor) throw new Error(`Unknown step type: ${step.type}`);

      const result = await Promise.race([
        executor(step, ctx, services),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error(`Step "${step.name}" timed out after ${timeoutMs}ms`)), timeoutMs)
        ),
      ]);

      return result;
    } catch (e) {
      lastError = e;
      console.log(`[DevBot Workflow] Step "${step.name}" attempt ${attempt}/${maxRetries} failed: ${e.message}`);
      if (attempt < maxRetries) {
        // Exponential backoff: 1s, 2s, 4s
        await new Promise(r => setTimeout(r, 1000 * Math.pow(2, attempt - 1)));
      }
    }
  }

  throw lastError;
}

// ─── Workflow Engine ────────────────────────────────────────────────────────

export class WorkflowEngine extends EventEmitter {
  /**
   * @param {Object} services - Injected service instances
   * @param {Object} services.engine - DevBotEngine instance
   * @param {Object} services.github - GitHubClient instance
   * @param {Object} services.slackBot - SlackBot instance
   */
  constructor(services = {}) {
    super();
    this.services = services;
    this.activeWorkflows = new Map();
    console.log('[DevBot Workflow] Engine initialized');
  }

  /**
   * Start a workflow from a template definition.
   * @param {Object} template - Workflow template with steps array
   * @param {Object} params - User-supplied parameters
   * @returns {Promise<Object>} The completed workflow state
   */
  async startWorkflow(template, params = {}) {
    if (!template || !template.steps || !Array.isArray(template.steps)) {
      throw new Error('Invalid workflow template: must have a steps array');
    }

    const workflowId = `wf-${crypto.randomUUID()}`;
    const now = new Date().toISOString();

    const workflow = {
      id: workflowId,
      templateId: template.id || 'custom',
      templateName: template.name || 'Custom Workflow',
      state: STATES.PENDING,
      params,
      steps: template.steps.map(s => ({
        ...s,
        state: STATES.PENDING,
        result: null,
        error: null,
        startedAt: null,
        completedAt: null,
        attempts: 0,
      })),
      results: {},
      metadata: {
        startedAt: now,
        completedAt: null,
        templateId: template.id,
        templateName: template.name,
      },
      createdAt: now,
      updatedAt: now,
    };

    this.activeWorkflows.set(workflowId, workflow);
    this.saveWorkflowState(workflow);
    this.emit('workflow:started', { workflowId, template: template.id });
    console.log(`[DevBot Workflow] Started workflow ${workflowId} (${template.name})`);

    // Execute asynchronously
    this.runWorkflow(workflow).catch(e => {
      console.error(`[DevBot Workflow] Fatal error in ${workflowId}: ${e.message}`);
    });

    return { workflowId, state: workflow.state };
  }

  /**
   * Execute the DAG of steps for a workflow.
   * @param {Object} workflow
   */
  async runWorkflow(workflow) {
    workflow.state = STATES.RUNNING;
    workflow.updatedAt = new Date().toISOString();
    this.saveWorkflowState(workflow);

    const ctx = {
      workflowId: workflow.id,
      params: workflow.params,
      results: workflow.results,
      metadata: workflow.metadata,
    };

    try {
      const completed = new Set();
      const steps = workflow.steps;
      let progress = true;

      while (progress && workflow.state === STATES.RUNNING) {
        progress = false;

        // Find steps that are ready to run (dependencies met, not yet completed)
        const readySteps = steps.filter(s => {
          if (s.state !== STATES.PENDING) return false;
          const deps = s.dependsOn || [];
          return deps.every(depId => completed.has(depId));
        });

        if (readySteps.length === 0 && steps.some(s => s.state === STATES.PENDING)) {
          // Deadlock or waiting for running steps
          const runningSteps = steps.filter(s => s.state === STATES.RUNNING);
          if (runningSteps.length === 0) {
            throw new Error('Workflow deadlock: pending steps have unmet dependencies');
          }
          break;
        }

        if (readySteps.length === 0) break;

        // Execute ready steps in parallel
        const execPromises = readySteps.map(async (step) => {
          // Check condition
          if (!evaluateCondition(step.condition, ctx)) {
            step.state = STATES.COMPLETED;
            step.result = { skipped: true, reason: 'Condition not met' };
            step.completedAt = new Date().toISOString();
            completed.add(step.id);
            this.emit('step:skipped', { workflowId: workflow.id, stepId: step.id });
            return;
          }

          step.state = STATES.RUNNING;
          step.startedAt = new Date().toISOString();
          step.attempts++;
          this.saveWorkflowState(workflow);

          try {
            const result = await executeStepWithRetry(step, ctx, this.services);
            step.state = STATES.COMPLETED;
            step.result = result;
            step.completedAt = new Date().toISOString();
            ctx.results[step.id] = result;
            workflow.results[step.id] = result;
            completed.add(step.id);
            this.emit('step:completed', { workflowId: workflow.id, stepId: step.id, result });
            console.log(`[DevBot Workflow] Step "${step.name}" completed`);
          } catch (e) {
            step.state = STATES.FAILED;
            step.error = e.message;
            step.completedAt = new Date().toISOString();
            this.emit('step:failed', { workflowId: workflow.id, stepId: step.id, error: e.message });
            console.error(`[DevBot Workflow] Step "${step.name}" failed: ${e.message}`);
            throw e;
          }
        });

        const settled = await Promise.allSettled(execPromises);
        const failures = settled.filter(r => r.status === 'rejected');

        if (failures.length > 0) {
          workflow.state = STATES.FAILED;
          workflow.updatedAt = new Date().toISOString();
          workflow.metadata.completedAt = workflow.updatedAt;
          workflow.metadata.error = failures[0].reason?.message || 'Step execution failed';
          this.saveWorkflowState(workflow);
          this.emit('workflow:failed', { workflowId: workflow.id, error: workflow.metadata.error });
          console.error(`[DevBot Workflow] Workflow ${workflow.id} FAILED`);
          return;
        }

        progress = true;
      }

      if (workflow.state === STATES.RUNNING) {
        workflow.state = STATES.COMPLETED;
        workflow.updatedAt = new Date().toISOString();
        workflow.metadata.completedAt = workflow.updatedAt;
        this.saveWorkflowState(workflow);
        this.emit('workflow:completed', { workflowId: workflow.id, results: workflow.results });
        console.log(`[DevBot Workflow] Workflow ${workflow.id} COMPLETED`);
      }
    } catch (e) {
      if (workflow.state !== STATES.FAILED && workflow.state !== STATES.CANCELLED) {
        workflow.state = STATES.FAILED;
        workflow.metadata.error = e.message;
        workflow.metadata.completedAt = new Date().toISOString();
        workflow.updatedAt = new Date().toISOString();
        this.saveWorkflowState(workflow);
        this.emit('workflow:failed', { workflowId: workflow.id, error: e.message });
      }
    } finally {
      this.activeWorkflows.delete(workflow.id);
    }
  }

  /**
   * Cancel a running workflow.
   * @param {string} workflowId
   * @returns {boolean}
   */
  cancelWorkflow(workflowId) {
    const workflow = this.activeWorkflows.get(workflowId) || this.loadWorkflowState(workflowId);
    if (!workflow) return false;
    if (workflow.state !== STATES.RUNNING && workflow.state !== STATES.PENDING && workflow.state !== STATES.WAITING) {
      return false;
    }
    workflow.state = STATES.CANCELLED;
    workflow.updatedAt = new Date().toISOString();
    workflow.metadata.completedAt = workflow.updatedAt;
    this.saveWorkflowState(workflow);
    this.activeWorkflows.delete(workflowId);
    this.emit('workflow:cancelled', { workflowId });
    console.log(`[DevBot Workflow] Workflow ${workflowId} CANCELLED`);
    return true;
  }

  /**
   * Get the current state of a workflow.
   * @param {string} workflowId
   * @returns {Object|null}
   */
  getWorkflow(workflowId) {
    return this.activeWorkflows.get(workflowId) || this.loadWorkflowState(workflowId);
  }

  /**
   * List all workflows with optional filters.
   * @param {Object} options
   * @param {string} [options.state] - Filter by state
   * @param {string} [options.templateId] - Filter by template
   * @param {number} [options.limit] - Max results (default 50)
   * @param {number} [options.offset] - Skip results (default 0)
   * @returns {Object} { workflows, total }
   */
  listWorkflows({ state, templateId, limit = 50, offset = 0 } = {}) {
    try {
      const files = readdirSync(WORKFLOWS_DIR).filter(f => f.startsWith('wf-') && f.endsWith('.json'));
      let workflows = files.map(f => {
        try {
          return JSON.parse(readFileSync(resolve(WORKFLOWS_DIR, f), 'utf8'));
        } catch { return null; }
      }).filter(Boolean);

      if (state) workflows = workflows.filter(w => w.state === state);
      if (templateId) workflows = workflows.filter(w => w.templateId === templateId);

      // Sort by most recent first
      workflows.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
      const total = workflows.length;

      return {
        workflows: workflows.slice(offset, offset + limit),
        total,
        limit,
        offset,
      };
    } catch {
      return { workflows: [], total: 0, limit, offset };
    }
  }

  /**
   * Get aggregated dashboard statistics.
   * @returns {Object}
   */
  getDashboardStats() {
    const { workflows } = this.listWorkflows({ limit: 10000 });
    const stats = {
      total: workflows.length,
      byState: {},
      byTemplate: {},
      activeCount: this.activeWorkflows.size,
      recentFailures: [],
      avgDurationMs: 0,
    };

    let totalDuration = 0;
    let completedCount = 0;

    for (const w of workflows) {
      stats.byState[w.state] = (stats.byState[w.state] || 0) + 1;
      const tplKey = w.templateName || w.templateId;
      if (!stats.byTemplate[tplKey]) {
        stats.byTemplate[tplKey] = { total: 0, completed: 0, failed: 0 };
      }
      stats.byTemplate[tplKey].total++;
      if (w.state === STATES.COMPLETED) {
        stats.byTemplate[tplKey].completed++;
        if (w.metadata?.startedAt && w.metadata?.completedAt) {
          totalDuration += new Date(w.metadata.completedAt) - new Date(w.metadata.startedAt);
          completedCount++;
        }
      }
      if (w.state === STATES.FAILED) {
        stats.byTemplate[tplKey].failed++;
        stats.recentFailures.push({
          id: w.id,
          template: tplKey,
          error: w.metadata?.error,
          failedAt: w.updatedAt,
        });
      }
    }

    stats.avgDurationMs = completedCount > 0 ? Math.round(totalDuration / completedCount) : 0;
    stats.recentFailures = stats.recentFailures.slice(0, 10);

    return stats;
  }

  // ─── Persistence ────────────────────────────────────────────────────────

  /**
   * Save workflow state to disk.
   * @param {Object} workflow
   */
  saveWorkflowState(workflow) {
    try {
      const filePath = resolve(WORKFLOWS_DIR, `${workflow.id}.json`);
      writeFileSync(filePath, JSON.stringify(workflow, null, 2), 'utf8');
    } catch (e) {
      console.error(`[DevBot Workflow] Failed to save state for ${workflow.id}: ${e.message}`);
    }
  }

  /**
   * Load workflow state from disk.
   * @param {string} workflowId
   * @returns {Object|null}
   */
  loadWorkflowState(workflowId) {
    try {
      const filePath = resolve(WORKFLOWS_DIR, `${workflowId}.json`);
      if (!existsSync(filePath)) return null;
      return JSON.parse(readFileSync(filePath, 'utf8'));
    } catch {
      return null;
    }
  }
}

export { STATES, STEP_TYPES, stepExecutors };
