/**
 * DevBot AI — Pre-built Workflow Templates
 *
 * 10 production-ready workflow templates covering the full DevBot ecosystem:
 * app generation, code review, trading, onboarding, dropshipping,
 * marketplace, security, affiliates, DevFone store, and chatbots.
 *
 * Each template is a DAG of steps with dependencies, conditions, and parameters.
 */

// ─── Template 1: Full App Pipeline ──────────────────────────────────────────
const fullAppPipeline = {
  id: 'full-app-pipeline',
  name: 'Full App Pipeline',
  description: 'Generate app -> AI review -> Fix issues -> Push to GitHub -> Notify Slack -> Deploy',
  category: 'development',
  estimatedDuration: '3-5 minutes',
  requiredParams: ['prompt'],
  steps: [
    {
      id: 'generate',
      type: 'ai_generate',
      name: 'Generate Application',
      params: { prompt: '{{params.prompt}}', language: '{{params.language}}', framework: '{{params.framework}}' },
      dependsOn: [],
    },
    {
      id: 'review',
      type: 'ai_review',
      name: 'AI Code Review',
      params: { sourceStep: 'generate', language: '{{params.language}}' },
      dependsOn: ['generate'],
    },
    {
      id: 'fix',
      type: 'ai_generate',
      name: 'Fix Review Issues',
      params: { prompt: 'Fix the following issues found in code review: {{results.review.review}}. Original prompt: {{params.prompt}}' },
      dependsOn: ['review'],
      condition: 'results.review && results.review.review',
    },
    {
      id: 'push',
      type: 'github_push',
      name: 'Push to GitHub',
      params: { repo: '{{params.repoName}}', description: 'Generated by DevBot: {{params.prompt}}', sourceStep: 'fix' },
      dependsOn: ['fix'],
    },
    {
      id: 'notify',
      type: 'slack_notify',
      name: 'Notify Slack',
      params: { channel: '{{params.slackChannel}}', message: 'App "{{params.prompt}}" deployed to GitHub: {{results.push.repoUrl}}' },
      dependsOn: ['push'],
    },
    {
      id: 'deploy_webhook',
      type: 'webhook_trigger',
      name: 'Trigger Deploy',
      params: { url: '{{params.deployUrl}}', method: 'POST', body: { repo: '{{results.push.repoName}}', action: 'deploy' } },
      dependsOn: ['push'],
      condition: 'params.deployUrl',
    },
  ],
};

// ─── Template 2: Code Review Loop ───────────────────────────────────────────
const codeReviewLoop = {
  id: 'code-review-loop',
  name: 'Code Review Loop',
  description: 'Submit code -> AI review -> Generate fixes -> Re-review -> Push PR -> Notify',
  category: 'development',
  estimatedDuration: '2-4 minutes',
  requiredParams: ['code'],
  steps: [
    {
      id: 'initial_review',
      type: 'ai_review',
      name: 'Initial Code Review',
      params: { code: '{{params.code}}', language: '{{params.language}}' },
      dependsOn: [],
    },
    {
      id: 'generate_fixes',
      type: 'ai_generate',
      name: 'Generate Fixes',
      params: { prompt: 'Refactor and fix the following code based on review feedback. Code: {{params.code}}. Review: {{results.initial_review.review}}' },
      dependsOn: ['initial_review'],
    },
    {
      id: 're_review',
      type: 'ai_review',
      name: 'Re-review Fixed Code',
      params: { sourceStep: 'generate_fixes' },
      dependsOn: ['generate_fixes'],
    },
    {
      id: 'push_pr',
      type: 'github_push',
      name: 'Push Pull Request',
      params: { repo: '{{params.repoName}}', description: 'Code review fixes by DevBot AI', sourceStep: 'generate_fixes' },
      dependsOn: ['re_review'],
    },
    {
      id: 'notify',
      type: 'slack_notify',
      name: 'Notify Team',
      params: { channel: '{{params.slackChannel}}', message: 'Code review complete. PR created: {{results.push_pr.repoUrl}}' },
      dependsOn: ['push_pr'],
    },
  ],
};

// ─── Template 3: Trading Setup ──────────────────────────────────────────────
const tradingSetup = {
  id: 'trading-setup',
  name: 'Trading Bot Setup',
  description: 'Create wallet -> Encrypt keys -> Configure strategy -> Start scheduler -> Monitor -> Alerts',
  category: 'trading',
  estimatedDuration: '1-2 minutes',
  requiredParams: ['userId', 'strategy'],
  steps: [
    {
      id: 'create_wallet',
      type: 'trading_execute',
      name: 'Create Trading Wallet',
      params: { action: 'create_wallet', params: { network: '{{params.network}}' } },
      dependsOn: [],
    },
    {
      id: 'encrypt_keys',
      type: 'vault_encrypt',
      name: 'Encrypt Wallet Keys',
      params: { userId: '{{params.userId}}', keyName: 'trading_wallet', sourceStep: 'create_wallet' },
      dependsOn: ['create_wallet'],
    },
    {
      id: 'configure_strategy',
      type: 'trading_execute',
      name: 'Configure Strategy',
      params: { action: 'configure_strategy', params: { strategy: '{{params.strategy}}', pairs: '{{params.pairs}}', amount: '{{params.amount}}' } },
      dependsOn: ['encrypt_keys'],
    },
    {
      id: 'start_scheduler',
      type: 'trading_execute',
      name: 'Start Trading Scheduler',
      params: { action: 'start_scheduler', params: { strategyId: '{{results.configure_strategy.strategyId}}', interval: '{{params.interval}}' } },
      dependsOn: ['configure_strategy'],
    },
    {
      id: 'setup_monitoring',
      type: 'webhook_trigger',
      name: 'Configure Monitoring',
      params: { url: '{{params.monitoringUrl}}', method: 'POST', body: { wallet: '{{results.create_wallet.walletId}}', alerts: true } },
      dependsOn: ['start_scheduler'],
      condition: 'params.monitoringUrl',
    },
    {
      id: 'slack_alert',
      type: 'slack_notify',
      name: 'Trading Bot Active Alert',
      params: { channel: '{{params.slackChannel}}', message: 'Trading bot configured: {{params.strategy}} strategy on {{params.pairs}}. Scheduler active.' },
      dependsOn: ['start_scheduler'],
    },
  ],
};

// ─── Template 4: Customer Onboarding ────────────────────────────────────────
const customerOnboarding = {
  id: 'customer-onboarding',
  name: 'Customer Onboarding',
  description: 'Stripe payment -> Credits -> Welcome email -> Slack notify -> GitHub repo -> Starter app',
  category: 'business',
  estimatedDuration: '2-3 minutes',
  requiredParams: ['customerId', 'email', 'plan'],
  steps: [
    {
      id: 'charge',
      type: 'stripe_charge',
      name: 'Process Payment',
      params: { amount: '{{params.amount}}', currency: 'usd', description: 'DevBot {{params.plan}} Plan', customerId: '{{params.customerId}}' },
      dependsOn: [],
    },
    {
      id: 'welcome_email',
      type: 'email_send',
      name: 'Send Welcome Email',
      params: {
        to: '{{params.email}}',
        subject: 'Welcome to DevBot AI - {{params.plan}} Plan',
        html: '<h1>Welcome to DevBot AI!</h1><p>Your {{params.plan}} plan is now active. Start building amazing apps today.</p><p>Your API key and dashboard access details are on their way.</p>',
      },
      dependsOn: ['charge'],
    },
    {
      id: 'slack_notify',
      type: 'slack_notify',
      name: 'Notify Team',
      params: { channel: '#customers', message: 'New customer onboarded: {{params.email}} ({{params.plan}} plan)' },
      dependsOn: ['charge'],
    },
    {
      id: 'create_repo',
      type: 'github_push',
      name: 'Create Starter Repo',
      params: { repo: 'devbot-{{params.plan}}-starter', description: 'DevBot starter template for {{params.email}}', isPrivate: true },
      dependsOn: ['charge'],
    },
    {
      id: 'generate_starter',
      type: 'ai_generate',
      name: 'Generate Starter App',
      params: { prompt: 'Create a starter web application template with DevBot AI integration, authentication, and a dashboard. Include setup instructions.' },
      dependsOn: ['create_repo'],
    },
  ],
};

// ─── Template 5: Dropship Fulfillment ───────────────────────────────────────
const dropshipFulfillment = {
  id: 'dropship-fulfillment',
  name: 'Dropship Fulfillment',
  description: 'Order received -> Validate payment -> Source supplier -> Shipping -> Create order -> Confirm -> Track',
  category: 'ecommerce',
  estimatedDuration: '1-2 minutes',
  requiredParams: ['orderId', 'productId', 'customerEmail'],
  steps: [
    {
      id: 'validate_payment',
      type: 'stripe_charge',
      name: 'Validate Payment',
      params: { amount: '{{params.amount}}', currency: '{{params.currency}}', description: 'Dropship order {{params.orderId}}' },
      dependsOn: [],
    },
    {
      id: 'source_supplier',
      type: 'webhook_trigger',
      name: 'Source from Supplier',
      params: { url: '{{params.supplierApiUrl}}', method: 'POST', body: { productId: '{{params.productId}}', quantity: '{{params.quantity}}' } },
      dependsOn: ['validate_payment'],
      condition: 'params.supplierApiUrl',
    },
    {
      id: 'create_order',
      type: 'dropship_order',
      name: 'Create Dropship Order',
      params: { productId: '{{params.productId}}', quantity: '{{params.quantity}}', shippingAddress: '{{params.shippingAddress}}' },
      dependsOn: ['validate_payment'],
    },
    {
      id: 'confirmation_email',
      type: 'email_send',
      name: 'Send Confirmation Email',
      params: {
        to: '{{params.customerEmail}}',
        subject: 'Order Confirmed - #{{params.orderId}}',
        html: '<h2>Order Confirmed!</h2><p>Your order #{{params.orderId}} has been placed. Order reference: {{results.create_order.orderId}}</p><p>You will receive shipping updates soon.</p>',
      },
      dependsOn: ['create_order'],
    },
    {
      id: 'track_delivery',
      type: 'webhook_trigger',
      name: 'Setup Delivery Tracking',
      params: { url: '{{params.trackingWebhookUrl}}', method: 'POST', body: { orderId: '{{results.create_order.orderId}}', email: '{{params.customerEmail}}' } },
      dependsOn: ['create_order'],
      condition: 'params.trackingWebhookUrl',
    },
  ],
};

// ─── Template 6: Marketplace Publish ────────────────────────────────────────
const marketplacePublish = {
  id: 'marketplace-publish',
  name: 'Marketplace Publish',
  description: 'Generate app -> Review quality -> Screenshot -> List on marketplace -> Notify seller',
  category: 'marketplace',
  estimatedDuration: '3-5 minutes',
  requiredParams: ['prompt', 'sellerEmail'],
  steps: [
    {
      id: 'generate',
      type: 'ai_generate',
      name: 'Generate Application',
      params: { prompt: '{{params.prompt}}', language: '{{params.language}}', framework: '{{params.framework}}' },
      dependsOn: [],
    },
    {
      id: 'quality_review',
      type: 'ai_review',
      name: 'Quality Review',
      params: { sourceStep: 'generate' },
      dependsOn: ['generate'],
    },
    {
      id: 'screenshot',
      type: 'webhook_trigger',
      name: 'Generate Screenshot',
      params: { url: '{{params.screenshotServiceUrl}}', method: 'POST', body: { html: '{{results.generate.files}}' } },
      dependsOn: ['generate'],
      condition: 'params.screenshotServiceUrl',
    },
    {
      id: 'list_marketplace',
      type: 'webhook_trigger',
      name: 'List on Marketplace',
      params: {
        url: '{{params.marketplaceApiUrl}}',
        method: 'POST',
        body: {
          name: '{{results.generate.name}}',
          description: '{{results.generate.description}}',
          price: '{{params.price}}',
          category: '{{params.category}}',
          seller: '{{params.sellerEmail}}',
        },
      },
      dependsOn: ['quality_review'],
      condition: 'params.marketplaceApiUrl',
    },
    {
      id: 'notify_seller',
      type: 'email_send',
      name: 'Notify Seller',
      params: {
        to: '{{params.sellerEmail}}',
        subject: 'Your app "{{results.generate.name}}" is live on the marketplace!',
        html: '<h2>Your App is Live!</h2><p>"{{results.generate.name}}" has been published on the DevBot Marketplace.</p><p>Quality score from AI review is available in your dashboard.</p>',
      },
      dependsOn: ['quality_review'],
    },
  ],
};

// ─── Template 7: Security Audit ─────────────────────────────────────────────
const securityAudit = {
  id: 'security-audit',
  name: 'Security Audit',
  description: 'Scan code -> Check dependencies -> Smart contract audit -> Generate report -> Email results',
  category: 'security',
  estimatedDuration: '2-4 minutes',
  requiredParams: ['code'],
  steps: [
    {
      id: 'code_scan',
      type: 'ai_review',
      name: 'Security Code Scan',
      params: { code: '{{params.code}}', language: '{{params.language}}' },
      dependsOn: [],
    },
    {
      id: 'dependency_check',
      type: 'webhook_trigger',
      name: 'Check Dependencies',
      params: { url: '{{params.dependencyCheckUrl}}', method: 'POST', body: { code: '{{params.code}}', type: 'dependency_audit' } },
      dependsOn: [],
      condition: 'params.dependencyCheckUrl',
    },
    {
      id: 'smart_contract_audit',
      type: 'ai_review',
      name: 'Smart Contract Audit',
      params: { code: '{{params.smartContractCode}}', language: 'solidity' },
      dependsOn: [],
      condition: 'params.smartContractCode',
    },
    {
      id: 'generate_report',
      type: 'ai_generate',
      name: 'Generate Audit Report',
      params: {
        prompt: 'Generate a comprehensive security audit report in HTML format. Code scan results: {{results.code_scan.review}}. Dependency results: {{results.dependency_check.data}}. Smart contract audit: {{results.smart_contract_audit.review}}. Include severity ratings, recommendations, and remediation steps.',
      },
      dependsOn: ['code_scan'],
    },
    {
      id: 'email_report',
      type: 'email_send',
      name: 'Email Audit Results',
      params: {
        to: '{{params.email}}',
        subject: 'DevBot Security Audit Report',
        html: '<h2>Security Audit Complete</h2><p>Your security audit has been completed. Summary of findings:</p><p>{{results.code_scan.review}}</p><p>Full report has been generated and is available in your dashboard.</p>',
      },
      dependsOn: ['generate_report'],
    },
  ],
};

// ─── Template 8: Affiliate Payout ───────────────────────────────────────────
const affiliatePayout = {
  id: 'affiliate-payout',
  name: 'Affiliate Payout',
  description: 'Calculate commissions -> Verify threshold -> Process payout -> Send receipt -> Update leaderboard',
  category: 'business',
  estimatedDuration: '30 seconds',
  requiredParams: ['affiliateId', 'affiliateEmail'],
  steps: [
    {
      id: 'calculate',
      type: 'webhook_trigger',
      name: 'Calculate Commissions',
      params: {
        url: '{{params.affiliateApiUrl}}',
        method: 'POST',
        body: { affiliateId: '{{params.affiliateId}}', action: 'calculate_commissions' },
      },
      dependsOn: [],
      condition: 'params.affiliateApiUrl',
    },
    {
      id: 'verify_threshold',
      type: 'trading_execute',
      name: 'Verify $50 Minimum Threshold',
      params: { action: 'verify_payout_threshold', params: { affiliateId: '{{params.affiliateId}}', minimumAmount: 5000 } },
      dependsOn: ['calculate'],
    },
    {
      id: 'process_payout',
      type: 'stripe_charge',
      name: 'Process Stripe Payout',
      params: { amount: '{{params.payoutAmount}}', currency: 'usd', description: 'Affiliate payout for {{params.affiliateId}}' },
      dependsOn: ['verify_threshold'],
      condition: 'results.verify_threshold && results.verify_threshold.executed',
    },
    {
      id: 'send_receipt',
      type: 'email_send',
      name: 'Send Payout Receipt',
      params: {
        to: '{{params.affiliateEmail}}',
        subject: 'DevBot Affiliate Payout Processed',
        html: '<h2>Payout Processed!</h2><p>Your affiliate commission payout of ${{params.payoutAmount}} has been processed via Stripe.</p><p>Transaction details are available in your affiliate dashboard.</p>',
      },
      dependsOn: ['process_payout'],
    },
    {
      id: 'update_leaderboard',
      type: 'webhook_trigger',
      name: 'Update Leaderboard',
      params: {
        url: '{{params.leaderboardUrl}}',
        method: 'POST',
        body: { affiliateId: '{{params.affiliateId}}', payout: '{{params.payoutAmount}}', action: 'update_leaderboard' },
      },
      dependsOn: ['process_payout'],
      condition: 'params.leaderboardUrl',
    },
  ],
};

// ─── Template 9: DevFone Store Order ────────────────────────────────────────
const devfoneStoreOrder = {
  id: 'devfone-store-order',
  name: 'DevFone Store Order',
  description: 'Cart validation -> Stripe charge -> Supplier order -> Shipping email -> Analytics',
  category: 'ecommerce',
  estimatedDuration: '1 minute',
  requiredParams: ['cartItems', 'customerEmail', 'totalAmount'],
  steps: [
    {
      id: 'validate_cart',
      type: 'trading_execute',
      name: 'Cart Validation',
      params: { action: 'validate_cart', params: { items: '{{params.cartItems}}', total: '{{params.totalAmount}}' } },
      dependsOn: [],
    },
    {
      id: 'charge',
      type: 'stripe_charge',
      name: 'Process Stripe Charge',
      params: { amount: '{{params.totalAmount}}', currency: 'usd', description: 'DevFone Store Order', customerId: '{{params.customerId}}' },
      dependsOn: ['validate_cart'],
    },
    {
      id: 'supplier_order',
      type: 'dropship_order',
      name: 'Place Supplier Order',
      params: { productId: '{{params.primaryProductId}}', quantity: '{{params.quantity}}', shippingAddress: '{{params.shippingAddress}}' },
      dependsOn: ['charge'],
    },
    {
      id: 'shipping_email',
      type: 'email_send',
      name: 'Shipping Confirmation Email',
      params: {
        to: '{{params.customerEmail}}',
        subject: 'Your DevFone order is on its way!',
        html: '<h2>Order Shipped!</h2><p>Your DevFone order ({{results.supplier_order.orderId}}) has been shipped.</p><p>Track your delivery with the tracking link in your account.</p>',
      },
      dependsOn: ['supplier_order'],
    },
    {
      id: 'analytics',
      type: 'webhook_trigger',
      name: 'Update Analytics',
      params: {
        url: '{{params.analyticsUrl}}',
        method: 'POST',
        body: { event: 'order_completed', amount: '{{params.totalAmount}}', orderId: '{{results.supplier_order.orderId}}' },
      },
      dependsOn: ['supplier_order'],
      condition: 'params.analyticsUrl',
    },
  ],
};

// ─── Template 10: AI Chatbot Deploy ─────────────────────────────────────────
const aiChatbotDeploy = {
  id: 'ai-chatbot-deploy',
  name: 'AI Chatbot Deploy',
  description: 'Configure persona -> Generate responses -> Test conversation -> Deploy endpoint -> Monitor',
  category: 'ai',
  estimatedDuration: '2-3 minutes',
  requiredParams: ['persona', 'businessName'],
  steps: [
    {
      id: 'configure_persona',
      type: 'ai_generate',
      name: 'Configure Bot Persona',
      params: {
        prompt: 'Create a chatbot system prompt/persona for "{{params.businessName}}". Persona: {{params.persona}}. Include greeting messages, FAQ responses, escalation rules, and tone guidelines. Return as a structured JSON config.',
      },
      dependsOn: [],
    },
    {
      id: 'generate_responses',
      type: 'ai_generate',
      name: 'Generate Response Templates',
      params: {
        prompt: 'Generate 20 common customer support response templates for a {{params.persona}} chatbot for "{{params.businessName}}". Include: greetings, FAQs, troubleshooting, pricing inquiries, and escalation responses. Return as JSON array.',
      },
      dependsOn: ['configure_persona'],
    },
    {
      id: 'test_conversation',
      type: 'ai_review',
      name: 'Test Conversation Flow',
      params: { sourceStep: 'configure_persona' },
      dependsOn: ['generate_responses'],
    },
    {
      id: 'deploy_endpoint',
      type: 'webhook_trigger',
      name: 'Deploy Chatbot Endpoint',
      params: {
        url: '{{params.deployUrl}}',
        method: 'POST',
        body: {
          persona: '{{results.configure_persona}}',
          responses: '{{results.generate_responses}}',
          businessName: '{{params.businessName}}',
        },
      },
      dependsOn: ['test_conversation'],
      condition: 'params.deployUrl',
    },
    {
      id: 'monitor_setup',
      type: 'slack_notify',
      name: 'Setup Monitoring Alert',
      params: { channel: '{{params.slackChannel}}', message: 'AI Chatbot for "{{params.businessName}}" deployed successfully. Monitoring active.' },
      dependsOn: ['test_conversation'],
    },
  ],
};

// ─── Template Registry ──────────────────────────────────────────────────────

/**
 * All available workflow templates indexed by ID.
 * @type {Object<string, Object>}
 */
const WORKFLOW_TEMPLATES = {
  'full-app-pipeline': fullAppPipeline,
  'code-review-loop': codeReviewLoop,
  'trading-setup': tradingSetup,
  'customer-onboarding': customerOnboarding,
  'dropship-fulfillment': dropshipFulfillment,
  'marketplace-publish': marketplacePublish,
  'security-audit': securityAudit,
  'affiliate-payout': affiliatePayout,
  'devfone-store-order': devfoneStoreOrder,
  'ai-chatbot-deploy': aiChatbotDeploy,
};

/**
 * Get a workflow template by ID.
 * @param {string} templateId
 * @returns {Object|null}
 */
export function getTemplate(templateId) {
  return WORKFLOW_TEMPLATES[templateId] || null;
}

/**
 * List all available workflow templates with metadata.
 * @returns {Object[]}
 */
export function listTemplates() {
  return Object.values(WORKFLOW_TEMPLATES).map(t => ({
    id: t.id,
    name: t.name,
    description: t.description,
    category: t.category,
    estimatedDuration: t.estimatedDuration,
    requiredParams: t.requiredParams,
    stepCount: t.steps.length,
  }));
}

export { WORKFLOW_TEMPLATES };
